import psycopg2
from google.colab import userdata

conn = psycopg2.connect(userdata.get("DB_URL"))
cur = conn.cursor()

# ── Top 100 Movies (Title, IMDB, Letterboxd, Rotten Tomatoes, Release Date, Genre)
movies = [
    ("The Shawshank Redemption",                          "9.3", "4.7", "91%",  "1994-09-23", "Drama"),
    ("The Godfather",                                     "9.2", "4.6", "97%",  "1972-03-24", "Crime/Drama"),
    ("The Dark Knight",                                   "9.0", "4.5", "94%",  "2008-07-18", "Action/Crime"),
    ("The Godfather Part II",                             "9.0", "4.5", "97%",  "1974-12-20", "Crime/Drama"),
    ("12 Angry Men",                                      "9.0", "4.4", "100%", "1957-04-10", "Drama"),
    ("Schindler's List",                                  "9.0", "4.5", "98%",  "1993-12-15", "Biography/Drama"),
    ("The Lord of the Rings: The Return of the King",    "9.0", "4.4", "93%",  "2003-12-17", "Adventure/Fantasy"),
    ("Pulp Fiction",                                      "8.9", "4.4", "92%",  "1994-10-14", "Crime/Drama"),
    ("The Lord of the Rings: The Fellowship of the Ring","8.9", "4.4", "91%",  "2001-12-19", "Adventure/Fantasy"),
    ("The Good, the Bad and the Ugly",                   "8.8", "4.4", "97%",  "1966-12-23", "Western"),
    ("Forrest Gump",                                      "8.8", "4.1", "71%",  "1994-07-06", "Drama/Romance"),
    ("Fight Club",                                        "8.8", "4.3", "79%",  "1999-10-15", "Drama/Thriller"),
    ("Inception",                                         "8.8", "4.2", "87%",  "2010-07-16", "Action/Sci-Fi"),
    ("The Lord of the Rings: The Two Towers",            "8.8", "4.4", "95%",  "2002-12-18", "Adventure/Fantasy"),
    ("The Matrix",                                        "8.7", "4.2", "88%",  "1999-03-31", "Action/Sci-Fi"),
    ("Goodfellas",                                        "8.7", "4.3", "96%",  "1990-09-19", "Biography/Crime"),
    ("One Flew Over the Cuckoo's Nest",                  "8.7", "4.2", "94%",  "1975-11-19", "Drama"),
    ("Se7en",                                             "8.6", "4.1", "65%",  "1995-09-22", "Crime/Mystery"),
    ("It's a Wonderful Life",                             "8.6", "4.1", "94%",  "1946-12-20", "Drama/Fantasy"),
    ("Seven Samurai",                                     "8.6", "4.4", "100%", "1954-04-26", "Action/Adventure"),
    ("The Silence of the Lambs",                         "8.6", "4.1", "95%",  "1991-02-14", "Crime/Thriller"),
    ("Saving Private Ryan",                               "8.6", "4.2", "93%",  "1998-07-24", "Drama/War"),
    ("City of God",                                       "8.6", "4.3", "91%",  "2002-08-30", "Crime/Drama"),
    ("Interstellar",                                      "8.7", "4.2", "72%",  "2014-11-07", "Adventure/Sci-Fi"),
    ("Life is Beautiful",                                 "8.6", "4.2", "80%",  "1997-12-20", "Comedy/Drama"),
    ("The Green Mile",                                    "8.6", "4.1", "78%",  "1999-12-10", "Crime/Drama"),
    ("Terminator 2: Judgment Day",                        "8.6", "4.1", "93%",  "1991-07-03", "Action/Sci-Fi"),
    ("Star Wars: Episode V - The Empire Strikes Back",   "8.7", "4.3", "94%",  "1980-06-20", "Action/Adventure"),
    ("The Pianist",                                       "8.5", "4.2", "96%",  "2002-09-24", "Biography/Drama"),
    ("Back to the Future",                                "8.5", "4.2", "96%",  "1985-07-03", "Adventure/Comedy"),
    ("Spirited Away",                                     "8.6", "4.4", "97%",  "2001-07-20", "Animation/Adventure"),
    ("Psycho",                                            "8.5", "4.2", "96%",  "1960-09-08", "Horror/Mystery"),
    ("Gladiator",                                         "8.5", "4.0", "76%",  "2000-05-05", "Action/Adventure"),
    ("The Lion King",                                     "8.5", "4.0", "93%",  "1994-06-24", "Animation/Drama"),
    ("American History X",                                "8.5", "4.1", "83%",  "1998-11-20", "Crime/Drama"),
    ("The Departed",                                      "8.5", "4.1", "91%",  "2006-10-06", "Crime/Drama"),
    ("Whiplash",                                          "8.5", "4.2", "94%",  "2014-10-10", "Drama/Music"),
    ("The Prestige",                                      "8.5", "4.1", "76%",  "2006-10-20", "Drama/Mystery"),
    ("Grave of the Fireflies",                            "8.5", "4.3", "97%",  "1988-04-16", "Animation/Drama"),
    ("Cinema Paradiso",                                   "8.5", "4.3", "90%",  "1988-11-17", "Drama/Romance"),
    ("Alien",                                             "8.5", "4.1", "98%",  "1979-06-22", "Horror/Sci-Fi"),
    ("Memento",                                           "8.4", "4.1", "93%",  "2000-09-05", "Mystery/Thriller"),
    ("Apocalypse Now",                                    "8.4", "4.2", "99%",  "1979-08-15", "Drama/War"),
    ("Raiders of the Lost Ark",                          "8.4", "4.1", "97%",  "1981-06-12", "Action/Adventure"),
    ("Django Unchained",                                  "8.4", "4.0", "87%",  "2012-12-25", "Drama/Western"),
    ("WALL-E",                                            "8.4", "4.2", "96%",  "2008-06-27", "Animation/Sci-Fi"),
    ("Paths of Glory",                                    "8.4", "4.2", "100%", "1957-12-25", "Drama/War"),
    ("The Shining",                                       "8.4", "4.1", "83%",  "1980-05-23", "Drama/Horror"),
    ("Sunset Blvd.",                                      "8.4", "4.3", "98%",  "1950-08-04", "Drama/Film-Noir"),
    ("Witness for the Prosecution",                       "8.4", "4.2", "100%", "1957-12-17", "Crime/Drama"),
    ("Dr. Strangelove",                                   "8.4", "4.3", "98%",  "1964-01-29", "Comedy/War"),
    ("Princess Mononoke",                                 "8.4", "4.3", "93%",  "1997-07-12", "Animation/Adventure"),
    ("Oldboy",                                            "8.4", "4.2", "80%",  "2003-11-21", "Action/Mystery"),
    ("The Dark Knight Rises",                             "8.4", "3.9", "87%",  "2012-07-20", "Action/Adventure"),
    ("Avengers: Infinity War",                            "8.4", "3.8", "85%",  "2018-04-27", "Action/Adventure"),
    ("Coco",                                              "8.4", "4.1", "97%",  "2017-11-22", "Animation/Family"),
    ("Once Upon a Time in the West",                      "8.5", "4.3", "95%",  "1968-12-21", "Western"),
    ("Once Upon a Time in the West",                      "8.5", "4.3", "95%",  "1968-12-21", "Western"),
    ("Casablanca",                                        "8.5", "4.2", "99%",  "1942-11-26", "Drama/Romance"),
    ("Full Metal Jacket",                                 "8.3", "4.0", "96%",  "1987-06-26", "Drama/War"),
    ("A Beautiful Mind",                                  "8.2", "3.9", "75%",  "2001-12-21", "Biography/Drama"),
    ("The Hunt",                                          "8.3", "4.1", "93%",  "2012-05-30", "Drama"),
    ("Braveheart",                                        "8.3", "3.9", "78%",  "1995-05-24", "Biography/Drama"),
    ("Toy Story",                                         "8.3", "4.1", "100%", "1995-11-22", "Animation/Comedy"),
    ("Good Will Hunting",                                 "8.3", "4.0", "97%",  "1997-12-05", "Drama/Romance"),
    ("Requiem for a Dream",                               "8.3", "4.1", "78%",  "2000-10-06", "Drama"),
    ("2001: A Space Odyssey",                             "8.3", "4.2", "92%",  "1968-04-02", "Sci-Fi"),
    ("The Intouchables",                                  "8.5", "4.2", "75%",  "2011-11-02", "Biography/Comedy"),
    ("Lawrence of Arabia",                                "8.3", "4.3", "98%",  "1962-12-10", "Adventure/Biography"),
    ("Reservoir Dogs",                                    "8.3", "4.1", "91%",  "1992-10-23", "Crime/Drama"),
    ("Eternal Sunshine of the Spotless Mind",            "8.3", "4.2", "93%",  "2004-03-19", "Drama/Romance"),
    ("For a Few Dollars More",                            "8.3", "4.1", "94%",  "1965-12-18", "Western"),
    ("A Clockwork Orange",                                "8.3", "4.1", "77%",  "1971-02-02", "Crime/Sci-Fi"),
    ("Singin' in the Rain",                               "8.3", "4.2", "100%", "1952-04-11", "Comedy/Musical"),
    ("Bicycle Thieves",                                   "8.3", "4.3", "99%",  "1948-11-24", "Drama"),
    ("Amadeus",                                           "8.3", "4.1", "93%",  "1984-09-19", "Biography/Drama"),
    ("Come and See",                                      "8.4", "4.5", "96%",  "1985-10-08", "Drama/War"),
    ("To Kill a Mockingbird",                             "8.3", "4.2", "99%",  "1962-12-25", "Drama"),
    ("Up",                                                "8.3", "4.0", "98%",  "2009-05-29", "Animation/Adventure"),
    ("Indiana Jones and the Last Crusade",               "8.2", "4.0", "88%",  "1989-05-24", "Action/Adventure"),
    ("Heat",                                              "8.3", "4.1", "86%",  "1995-12-15", "Action/Crime"),
    ("Parasite",                                          "8.5", "4.3", "99%",  "2019-05-30", "Comedy/Drama"),
    ("Star Wars: Episode IV - A New Hope",               "8.6", "4.1", "93%",  "1977-05-25", "Action/Adventure"),
    ("Taxi Driver",                                       "8.2", "4.1", "96%",  "1976-02-08", "Crime/Drama"),
    ("Monty Python and the Holy Grail",                  "8.2", "4.0", "97%",  "1975-05-25", "Adventure/Comedy"),
    ("Batman Begins",                                     "8.2", "3.9", "84%",  "2005-06-15", "Action/Adventure"),
    ("The Wolf of Wall Street",                           "8.2", "3.9", "77%",  "2013-12-25", "Biography/Comedy"),
    ("Joker",                                             "8.4", "3.9", "68%",  "2019-10-04", "Crime/Drama"),
    ("Some Like It Hot",                                  "8.2", "4.1", "95%",  "1959-03-29", "Comedy/Romance"),
    ("3 Idiots",                                          "8.4", "4.0", "100%", "2009-12-25", "Comedy/Drama"),
    ("Double Indemnity",                                  "8.3", "4.2", "97%",  "1944-09-06", "Crime/Film-Noir"),
    ("Toy Story 3",                                       "8.3", "4.1", "98%",  "2010-06-18", "Animation/Comedy"),
    ("The Great Dictator",                                "8.4", "4.2", "95%",  "1940-10-15", "Comedy/Drama"),
    ("L.A. Confidential",                                 "8.2", "4.1", "99%",  "1997-09-19", "Crime/Mystery"),
    ("Inglourious Basterds",                              "8.3", "4.1", "88%",  "2009-08-21", "Adventure/Drama"),
    ("Harakiri",                                          "8.6", "4.4", "100%", "1962-09-16", "Action/Drama"),
    ("Ran",                                               "8.2", "4.3", "96%",  "1985-06-01", "Action/Drama"),
    ("The Truman Show",                                   "8.1", "4.0", "95%",  "1998-06-05", "Comedy/Drama"),
    ("Catch Me If You Can",                               "8.1", "3.9", "96%",  "2002-12-25", "Biography/Crime"),
    ("There Will Be Blood",                               "8.2", "4.2", "91%",  "2007-12-26", "Drama/Western"),
]

# ── Movie_Info data (Director, Actor1, Actor2, Actor3, Description)
info = [
    ("Frank Darabont",         "Tim Robbins",          "Morgan Freeman",       "Bob Gunton",           "Two imprisoned men bond over years, finding solace and redemption through acts of common decency."),
    ("Francis Ford Coppola",   "Marlon Brando",        "Al Pacino",            "James Caan",           "The aging patriarch of an organized crime dynasty transfers control to his reluctant son."),
    ("Christopher Nolan",      "Christian Bale",       "Heath Ledger",         "Aaron Eckhart",        "Batman faces the Joker, a criminal mastermind who plunges Gotham City into anarchy."),
    ("Francis Ford Coppola",   "Al Pacino",            "Robert De Niro",       "Robert Duvall",        "The early life of Vito Corleone and the story of Michael Corleone's rise as head of the family."),
    ("Sidney Lumet",           "Henry Fonda",          "Lee J. Cobb",          "Martin Balsam",        "A jury holdout attempts to prevent a miscarriage of justice in a murder case."),
    ("Steven Spielberg",       "Liam Neeson",          "Ralph Fiennes",        "Ben Kingsley",         "A businessman saves over a thousand Polish Jews from the Holocaust."),
    ("Peter Jackson",          "Elijah Wood",          "Viggo Mortensen",      "Ian McKellen",         "Gandalf and Aragorn lead the world of Men against Sauron's army to distract him from Frodo."),
    ("Quentin Tarantino",      "John Travolta",        "Uma Thurman",          "Samuel L. Jackson",    "The lives of two mob hitmen, a boxer, and a pair of diner bandits intertwine in four tales."),
    ("Peter Jackson",          "Elijah Wood",          "Ian McKellen",         "Orlando Bloom",        "A meek hobbit and companions set out on a journey to destroy the powerful One Ring."),
    ("Sergio Leone",           "Clint Eastwood",       "Eli Wallach",          "Lee Van Cleef",        "A bounty hunter and a bandit search for a buried cache of Confederate gold."),
    ("Robert Zemeckis",        "Tom Hanks",            "Robin Wright",         "Gary Sinise",          "The presidencies of Kennedy and Johnson through the eyes of Forrest Gump."),
    ("David Fincher",          "Brad Pitt",            "Edward Norton",        "Helena Bonham Carter", "An insomniac and a soap salesman form an underground fight club that evolves into something more."),
    ("Christopher Nolan",      "Leonardo DiCaprio",    "Joseph Gordon-Levitt", "Elliot Page",          "A thief who steals corporate secrets through dream-sharing is given the task of planting an idea."),
    ("Peter Jackson",          "Elijah Wood",          "Viggo Mortensen",      "Orlando Bloom",        "While Frodo and Sam edge closer to Mordor, the divided fellowship makes new allies for war."),
    ("Lana Wachowski",         "Keanu Reeves",         "Laurence Fishburne",   "Carrie-Anne Moss",     "A hacker learns that reality is a simulation and joins a rebellion against machine controllers."),
    ("Martin Scorsese",        "Ray Liotta",           "Robert De Niro",       "Joe Pesci",            "The story of Henry Hill and his life in the mob from childhood to becoming an FBI informant."),
    ("Milos Forman",           "Jack Nicholson",       "Louise Fletcher",      "Brad Dourif",          "A criminal pleads insanity and is placed in a mental institution where he rebels against the nurse."),
    ("David Fincher",          "Brad Pitt",            "Morgan Freeman",       "Kevin Spacey",         "Two detectives hunt a serial killer who uses the seven deadly sins as his motives."),
    ("Frank Capra",            "James Stewart",        "Donna Reed",           "Lionel Barrymore",     "An angel helps a compassionate but suicidal businessman see what life would be like without him."),
    ("Akira Kurosawa",         "Toshiro Mifune",       "Takashi Shimura",      "Keiko Tsushima",       "A poor village hires seven samurai to combat bandits who steal their crops."),
    ("Jonathan Demme",         "Jodie Foster",         "Anthony Hopkins",      "Scott Glenn",          "A young FBI cadet seeks the help of imprisoned cannibal Hannibal Lecter to catch another killer."),
    ("Steven Spielberg",       "Tom Hanks",            "Tom Sizemore",         "Edward Burns",         "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper."),
    ("Fernando Meirelles",     "Alexandre Rodrigues",  "Leandro Firmino",      "Phellipe Haagensen",   "The story of how crime and drug lords come to rule a housing project in Rio de Janeiro."),
    ("Christopher Nolan",      "Matthew McConaughey",  "Anne Hathaway",        "Jessica Chastain",     "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival."),
    ("Roberto Benigni",        "Roberto Benigni",      "Nicoletta Braschi",    "Giorgio Cantarini",    "When an open-minded Jewish man and his son are captured by Nazis, he uses imagination to protect his son."),
    ("Frank Darabont",         "Tom Hanks",            "Michael Clarke Duncan","David Morse",          "The lives of guards on Death Row are affected by one of their charges: a black man accused of murder."),
    ("James Cameron",          "Arnold Schwarzenegger","Linda Hamilton",        "Robert Patrick",       "A cyborg from the future is sent back in time to protect the future leader of the human resistance."),
    ("Irvin Kershner",         "Mark Hamill",          "Harrison Ford",        "Carrie Fisher",        "After the Empire strikes back, Luke trains with Yoda while his friends are pursued across the galaxy."),
    ("Roman Polanski",         "Adrien Brody",         "Thomas Kretschmann",   "Frank Finlay",         "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II."),
    ("Robert Zemeckis",        "Michael J. Fox",       "Christopher Lloyd",    "Lea Thompson",         "A teenager is accidentally sent back in time and must ensure his parents meet while returning to 1985."),
    ("Hayao Miyazaki",         "Daveigh Chase",        "Suzanne Pleshette",    "Miyu Irino",           "A young girl enters a spirit world and must work to free her parents who have been turned into pigs."),
    ("Alfred Hitchcock",       "Anthony Perkins",      "Janet Leigh",          "Vera Miles",           "A secretary on the run checks into a remote motel run by a young man under his mother's influence."),
    ("Ridley Scott",           "Russell Crowe",        "Joaquin Phoenix",      "Connie Nielsen",       "A Roman general becomes a slave, a gladiator, and ultimately seeks revenge against the emperor."),
    ("Roger Allers",           "Matthew Broderick",    "Jeremy Irons",         "James Earl Jones",     "Lion prince Simba flees his kingdom after the murder of his father and must reclaim his throne."),
    ("Tony Kaye",              "Edward Norton",        "Edward Furlong",       "Beverly D'Angelo",     "A former neo-Nazi skinhead tries to prevent his younger brother from going down the same path."),
    ("Martin Scorsese",        "Leonardo DiCaprio",    "Matt Damon",           "Jack Nicholson",       "An undercover cop and a mole in the police attempt to identify each other while in a crime gang."),
    ("Damien Chazelle",        "Miles Teller",         "J.K. Simmons",         "Paul Reiser",          "A promising young drummer enrolls at a cutthroat music conservatory where a ruthless instructor pushes him."),
    ("Christopher Nolan",      "Hugh Jackman",         "Christian Bale",       "Michael Caine",        "Two rival magicians engage in a battle of wits and sabotage to create the best illusion."),
    ("Isao Takahata",          "Tsutomu Tatsumi",      "Ayano Shiraishi",      "Akemi Yamaguchi",      "A young boy and his little sister struggle to survive in Japan during World War II."),
    ("Giuseppe Tornatore",     "Philippe Noiret",      "Jacques Perrin",       "Salvatore Cascio",     "A filmmaker recalls his childhood when he fell in love with cinema in a Sicilian village."),
    ("Ridley Scott",           "Sigourney Weaver",     "Tom Skerritt",         "John Hurt",            "The crew of a commercial spacecraft encounters a deadly extraterrestrial creature on a remote planet."),
    ("Christopher Nolan",      "Guy Pearce",           "Carrie-Anne Moss",     "Joe Pantoliano",       "A man with short-term memory loss uses notes to hunt for his wife's killer."),
    ("Francis Ford Coppola",   "Marlon Brando",        "Martin Sheen",         "Robert Duvall",        "During the Vietnam War, a captain is sent to terminate the command of a rogue Special Forces colonel."),
    ("Steven Spielberg",       "Harrison Ford",        "Karen Allen",          "Paul Freeman",         "An archaeologist races to find the Ark of the Covenant before the Nazis can use its powers."),
    ("Quentin Tarantino",      "Jamie Foxx",           "Christoph Waltz",      "Leonardo DiCaprio",    "A freed slave teams with a bounty hunter to rescue his wife from a brutal plantation owner."),
    ("Andrew Stanton",         "Ben Burtt",            "Elissa Knight",        "Jeff Garlin",          "A small waste-collecting robot falls in love and embarks on a journey that determines humanity's fate."),
    ("Stanley Kubrick",        "Kirk Douglas",         "Ralph Meeker",         "Adolphe Menjou",       "A French colonel defends his soldiers against a charge of cowardice during World War I."),
    ("Stanley Kubrick",        "Jack Nicholson",       "Shelley Duvall",       "Danny Lloyd",          "A family heads to an isolated hotel for the winter where a sinister presence drives the father insane."),
    ("Billy Wilder",           "William Holden",       "Gloria Swanson",       "Erich von Stroheim",   "A screenwriter becomes entangled with a faded silent film star who dreams of a comeback."),
    ("Billy Wilder",           "Tyrone Power",         "Marlene Dietrich",     "Charles Laughton",     "A barrister is hired to defend a man accused of murder in a sensational trial."),
    ("Stanley Kubrick",        "Peter Sellers",        "George C. Scott",      "Sterling Hayden",      "An Air Force general orders a nuclear attack on the Soviet Union, and the President tries to stop it."),
    ("Hayao Miyazaki",         "Yoji Matsuda",         "Yuriko Ishida",        "Yuko Tanaka",          "A prince seeks a cure for a wound while becoming embroiled in a war between a forest god and a mining colony."),
    ("Park Chan-wook",         "Choi Min-sik",         "Yoo Ji-tae",           "Kang Hye-jung",        "After being kidnapped and imprisoned for 15 years, a man is released and seeks revenge on his captor."),
    ("Christopher Nolan",      "Christian Bale",       "Tom Hardy",            "Anne Hathaway",        "Eight years after the Joker's reign of chaos, Batman is forced out of exile to battle the terrorist Bane."),
    ("Anthony Russo",          "Robert Downey Jr.",    "Chris Hemsworth",      "Mark Ruffalo",         "The Avengers and their allies must be willing to sacrifice all to defeat Thanos before he destroys reality."),
    ("Lee Unkrich",            "Tom Hanks",            "Tim Allen",            "Ned Beatty",           "When Woody and his friends end up in a daycare center, they must find a way back to their owner Andy."),
    ("Lee Unkrich",            "Anthony Gonzalez",     "Gael Garcia Bernal",   "Benjamin Bratt",       "Aspiring musician Miguel is transported to the Land of the Dead where he seeks his great-great-grandfather."),
    ("Sergio Leone",           "Henry Fonda",          "Charles Bronson",      "Claudia Cardinale",    "A mysterious stranger with a harmonica joins forces with a notorious desperado to protect a widow."),
    ("Michael Curtiz",         "Humphrey Bogart",      "Ingrid Bergman",       "Paul Henreid",         "A cynical nightclub owner protects an old flame and her fugitive husband from Nazis in WWII Morocco."),
    ("Stanley Kubrick",        "Matthew Modine",       "R. Lee Ermey",         "Vincent D'Onofrio",    "The story of a group of young men going through Marine boot camp and the Vietnam War."),
    ("Ron Howard",             "Russell Crowe",        "Jennifer Connelly",    "Ed Harris",            "A brilliant mathematician's life is complicated by his struggle with schizophrenia."),
    ("Thomas Vinterberg",      "Mads Mikkelsen",       "Thomas Bo Larsen",     "Annika Wedderkopp",    "A man's life is shattered when a child falsely accuses him of abuse."),
    ("Mel Gibson",             "Mel Gibson",           "Sophie Marceau",       "Patrick McGoohan",     "Scottish warrior William Wallace leads a revolt against English rule in 13th-century Scotland."),
    ("John Lasseter",          "Tom Hanks",            "Tim Allen",            "Don Rickles",          "A cowboy toy is threatened when a new spaceman toy supplants him as the owner's favorite."),
    ("Gus Van Sant",           "Robin Williams",       "Matt Damon",           "Ben Affleck",          "A janitor at MIT solves a difficult math problem and a therapist helps him find direction in life."),
    ("Darren Aronofsky",       "Ellen Burstyn",        "Jared Leto",           "Jennifer Connelly",    "The drug-induced journeys of four Coney Island characters are depicted with haunting realism."),
    ("Stanley Kubrick",        "Keir Dullea",          "Gary Lockwood",        "William Sylvester",    "After discovering a mysterious artifact, humanity sets off on a quest for its origins."),
    ("Olivier Nakache",        "Francois Cluzet",      "Omar Sy",              "Anne Le Ny",           "After a quadriplegic aristocrat hires an ex-con as his caregiver, an unlikely friendship develops."),
    ("David Lean",             "Peter O'Toole",        "Alec Guinness",        "Anthony Quinn",        "T.E. Lawrence unites Arab tribes to fight the Ottoman Turks during World War I."),
    ("Quentin Tarantino",      "Harvey Keitel",        "Tim Roth",             "Michael Madsen",       "After a diamond heist goes wrong, the surviving criminals distrust each other."),
    ("Michel Gondry",          "Jim Carrey",           "Kate Winslet",         "Kirsten Dunst",        "A couple undergo a procedure to erase each other from their memories after a painful breakup."),
    ("Sergio Leone",           "Clint Eastwood",       "Lee Van Cleef",        "Gian Maria Volonte",   "Two bounty hunters work together to track down a Mexican outlaw and his gang."),
    ("Stanley Kubrick",        "Malcolm McDowell",     "Patrick Magee",        "Michael Bates",        "In the future, a criminal is cured of violence through experimental treatment and faces a changed world."),
    ("Stanley Donen",          "Gene Kelly",           "Donald O'Connor",      "Debbie Reynolds",      "A silent film star falls for a chorus girl while his studio struggles to convert to talking pictures."),
    ("Vittorio De Sica",       "Lamberto Maggiorani",  "Enzo Staiola",         "Lianella Carell",      "A poor man's bicycle is stolen, threatening his livelihood and driving him to desperate measures."),
    ("Milos Forman",           "F. Murray Abraham",    "Tom Hulce",            "Elizabeth Berridge",   "Court composer Salieri schemes against the brilliant but uncouth Wolfgang Amadeus Mozart."),
    ("Elem Klimov",            "Aleksey Kravchenko",   "Olga Mironova",        "Liubomiras Laucevicius","A Belarusian boy witnesses the atrocities of World War II Nazi occupation."),
    ("Robert Mulligan",        "Gregory Peck",         "Mary Badham",          "Phillip Alford",       "Lawyer Atticus Finch defends a Black man accused of rape in the Deep South."),
    ("Pete Docter",            "Edward Asner",         "Jordan Nagai",         "John Ratzenberger",    "An elderly widower travels to South America in a flying house with a young stowaway."),
    ("Steven Spielberg",       "Harrison Ford",        "Sean Connery",         "Denholm Elliott",      "Indiana Jones and his father embark on a quest to find the Holy Grail."),
    ("Michael Mann",           "Al Pacino",            "Robert De Niro",       "Val Kilmer",           "A top thief and a veteran detective collide as the thief plans his last big job."),
    ("Bong Joon-ho",           "Song Kang-ho",         "Lee Sun-kyun",         "Cho Yeo-jeong",        "A poor family schemes to become employed by a wealthy family and a class-war soon unfolds."),
    ("George Lucas",           "Mark Hamill",          "Harrison Ford",        "Carrie Fisher",        "Luke Skywalker joins rebel forces to fight the Galactic Empire and destroy their superweapon."),
    ("Martin Scorsese",        "Robert De Niro",       "Jodie Foster",         "Cybill Shepherd",      "A mentally unstable veteran works as a nighttime taxi driver in New York City's degenerate hell."),
    ("Terry Gilliam",          "Graham Chapman",       "John Cleese",          "Eric Idle",            "King Arthur and his Knights of the Round Table embark on a low-budget search for the Holy Grail."),
    ("Christopher Nolan",      "Christian Bale",       "Michael Caine",        "Liam Neeson",          "Bruce Wayne's mentor trains him to fight injustice, and he becomes Batman to defend Gotham."),
    ("Martin Scorsese",        "Leonardo DiCaprio",    "Jonah Hill",           "Margot Robbie",        "Based on Jordan Belfort's rise and fall as a corrupt stockbroker on Wall Street."),
    ("Todd Phillips",          "Joaquin Phoenix",      "Robert De Niro",       "Zazie Beetz",          "A failed comedian descends into madness and becomes the criminal mastermind known as the Joker."),
    ("Billy Wilder",           "Jack Lemmon",          "Tony Curtis",          "Marilyn Monroe",       "Two musicians witness a mob murder and flee, disguised as members of an all-female band."),
    ("Rajkumar Hirani",        "Aamir Khan",           "Madhavan",             "Sharman Joshi",        "Two friends search for their long-lost pal and reminisce about their college days."),
    ("Billy Wilder",           "Fred MacMurray",       "Barbara Stanwyck",     "Edward G. Robinson",   "An insurance salesman plots with a woman to murder her husband for the insurance money."),
    ("Lee Unkrich",            "Tom Hanks",            "Tim Allen",            "Joan Cusack",          "Andy's toys must escape from a daycare center after being accidentally donated."),
    ("Charles Chaplin",        "Charles Chaplin",      "Paulette Goddard",     "Jack Oakie",           "The Jewish barber and Adenoid Hynkel, the dictator of Tomainia, are look-alikes in this satirical comedy."),
    ("Curtis Hanson",          "Kevin Spacey",         "Russell Crowe",        "Guy Pearce",           "Two LAPD detectives investigate a murder that draws them into a web of police corruption in 1953 Los Angeles."),
    ("Quentin Tarantino",      "Brad Pitt",            "Christoph Waltz",      "Michael Fassbender",   "In Nazi-occupied France, a group of Jewish U.S. soldiers plan to assassinate Nazi leaders."),
    ("Masaki Kobayashi",       "Tatsuya Nakadai",      "Akira Ishihama",       "Shima Iwashita",       "A ronin asks to commit ritual suicide at a feudal lord's home, uncovering a conspiracy."),
    ("Akira Kurosawa",         "Tatsuya Nakadai",      "Akira Terao",          "Jinpachi Nezu",        "An aging warlord retires and divides his kingdom among his three sons, leading to betrayal."),
    ("Peter Weir",             "Jim Carrey",           "Laura Linney",         "Ed Harris",            "An insurance salesman discovers his whole life is a TV show."),
    ("Steven Spielberg",       "Leonardo DiCaprio",    "Tom Hanks",            "Christopher Walken",   "The story of Frank Abagnale Jr., who successfully conned millions as a pilot, doctor, and prosecutor."),
    ("Paul Thomas Anderson",   "Daniel Day-Lewis",     "Paul Dano",            "Kevin J. O'Connor",    "A story of family, religion, and oil following a prospector who strikes it rich in California."),
]

# ── Insert movies
print("Inserting movies...")
movie_ids = []
for m in movies:
    cur.execute("""
        INSERT INTO Top_100_Movies (Title, IMDB, Letterboxd, Rotten_Tomatoes, Date_Released, Genre)
        VALUES (%s, %s, %s, %s, %s, %s)
        RETURNING Movie_ID;
    """, m)
    movie_ids.append(cur.fetchone()[0])

# ── Insert info
print("Inserting movie info...")
for i, inf in enumerate(info):
    cur.execute("""
        INSERT INTO Movie_Info (Movie_ID, Director, Actor1, Actor2, Actor3, Description)
        VALUES (%s, %s, %s, %s, %s, %s);
    """, (movie_ids[i], *inf))

conn.commit()
print(f"✅ Done! {len(movies)} movies and info records inserted.")

cur.close()
conn.close()
